### PR TITLE
Switch from adm-zip to archiver.

### PR DESCRIPTION
**Pull request by arlaneenalra**
See: https://github.com/cthackers/adm-zip/issues/71

I ran into the above listed issue while attempting to package a Cordova application. In particular most of my images would extract as 0 byte files. Switching adm-zip out with archiver appears to fix the issue.

### CODE REVIEW

**Comment by amikula** [comment]
Why was this closed? cordova-browser's zip file still corrupts files. As far as I can tell, it hasn't been fixed anywhere, including in adm-zip.

**Comment by josergcatmisatravelcom** [comment]
Yeah! Why was this closed? just checked in Mac and in Windows and the same files are packed corrupted

**Comment by josergcatmisatravelcom** [comment]
Actually the new version is not visible through "cordova platform"

....>cordova platform add firefoxos@3.7
Error: Failed to fetch platform firefoxos@3.7
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: No compatible version found: cordova-firefoxos@'>=3.7.0 <3.8.0'
Valid install targets:
["3.5.0","3.6.0","3.6.0-dev","3.6.1","3.6.3"]

**Comment by josergcatmisatravelcom** [comment]
I had to patch my project to use the latest version. Remove the platform with "cordova platform remove firefoxos", then add it back with "cordova platform add firefoxos@https://github.com/apache/cordova-firefoxos.git".
Reference https://cordova.apache.org/docs/en/latest/platform_plugin_versioning_ref/index.html

**Comment by TimBarham** [comment]
@amikula - this PR was closed by a commit made to `cordova-firefoxos`, which was probably done by mistake.

But regarding this problem specifically: since it was last released, `cordova-browser` has been updated to use the `cordova-serve`, which in turn uses ExpressJS for things including handling compression. So this PR is out-of-date, and likely the problem will go away when we do another `cordova-browser` release (which I will kick off the process for).

In the meantime, you could try the latest changes to `cordova-browser` (including verifying this problem is now fixed) by adding the browser platform using:

    cordova add platform browser@https://github.com/apache/cordova-browser --save

**Pull request closed without merging**
