### PR TITLE
corrected path for config.xml

### PR DESCRIPTION
**Pull request by ketanyekale**
### Checklist
- [ ] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [ ] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by janpio** [comment]
What does this do?
And why?

**Comment by goffioul** [comment]
I had to apply the same type of change, so I guess my scenario was similar. The problems comes when you want to serve the cordova app using a non-empty URL prefix, for instance by deploying the app in apache, let's say the app is accessed using the URL `http://www.example.com/myapp/index.html`.

**Comment by royalrex** [comment]
Just found this fix. Was having the same problem of running a cordova (ionic) web app from a subdir and it failed to load config.xml and consequently the cordova splashscreen plugin was unable to load it's config params from config.xml.

Unless there is a really good reason why it's using absolute path, I think relative path is better.

**Comment by stevengill** [comment]
Thanks!!

**Comment by ketanyekale** [comment]
Thank you @stevengill

**Pull request merged**
